#!/usr/bin/env bash
# Avoid unnecessary reboots: don't notify if an updated package is
# - not currently running (e.g. alternative kernel)
# - not in use (e.g. alternative driver)
targets=$(tee /dev/null)  # targets from the hook (stdin)
kernelname="$(cat /lib/modules/"$(uname -r)"/pkgbase)"

for target in $targets ; do
    case "$target" in
        "$kernelname")
            notify=yes
            break
            ;;
        btrfs-progs)
            if [ -n "$(mount -t btrfs)" ]; then
                notify=yes
                break
            fi
            ;;
        xfsprogs)
            if [ -n "$(mount -t xfs)" ]; then
                notify=yes
                break
            fi
            ;;
        e2fsprogs)
            if [ -n "$(mount -t ext4)" ]; then
                notify=yes
                break
            fi
            ;;
        *)
            notify=yes
            break
            ;;
    esac
done

if [ -n "$notify" ] ; then
    exec /usr/bin/cachyos-reboot-required
fi
