#!/bin/bash

# To be called from cachyos-reboot-required.hook.

# Implementation using libnotify.

_get_users() { /usr/bin/users | sed 's| |\n|g' | sort | uniq ; }

_other_reboot_required() {
    local header="CachyOS Update"
    local title="Reboot recommended!"
    local msg="Reboot is recommended due to the upgrade of core system package(s)."

    # at TTY
    echo "==> INFO: $msg" >&2

    # notification
    local user userid cmd

    # Don't call notify-send in tty
    if [[ "$(tty)" =~ /dev/tty.* ]]; then
        return
    fi

    for user in $(_get_users) ; do
        userid="$(/usr/bin/id -u "$user")"
        cmd=(
            DISPLAY=:0
            DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${userid}/bus"
            /usr/bin/notify-send
            --icon=system-reboot
            --urgency=critical
            --app-name "'$header'"
            "'$title'"
            "'$msg'"
        )
        /usr/bin/su "$user" -c "${cmd[*]}"
    done
}
_other_reboot_required
unset -f _other_reboot_required
