#!/usr/bin/env bash
# Avoid unnecessary reboots: don't notify if an updated package is
# - not currently running (e.g. alternative kernel)
# - not in use (e.g. alternative driver)
targets=$(tee /dev/null)  # targets from the hook (stdin)
kernelname="$(cat /lib/modules/"$(uname -r)"/pkgbase)"

for target in $targets ; do
    case "$target" in
        "$kernelname")
            notify=yes ;;
        btrfs-progs)
            [ -n "$(mount -t btrfs)" ] && notify=yes ;;
        xfsprogs)
            [ -n "$(mount -t xfs)" ] && notify=yes ;;
        e2fsprogs)
            [ -n "$(mount -t ext4)" ] && notify=yes ;;
        *) notify=yes ;;
    esac
done

[ -n "$notify" ] && exec /usr/bin/cachyos-reboot-required
