#!/usr/bin/env bash
# To be called from cachyos-reboot-required.hook.
# Implementation using busctl.

header="CachyOS Update"
title="Reboot recommended!"
msg="Reboot is recommended due to the upgrade of core system package(s)."

# at TTY
echo "==> INFO: $msg" >&2

for user in $(users | sed 's| |\n|g' | sort | uniq); do
    # See https://specifications.freedesktop.org/notification-spec/1.2/protocol.html#command-notify
    busctl --machine="${user}@.host" --user call org.freedesktop.Notifications \
        /org/freedesktop/Notifications \
        org.freedesktop.Notifications  \
        Notify susssasa\{sv\}i \
        "$header" \
        0 \
        system-reboot \
        "$title" \
        "$msg" \
        0 \
        1 urgency y 0x2 \
        10000 &>/dev/null || true
done
