#!/usr/bin/env bash
# Run cachyos hooks related commands.

update_lsb_release() {
    sed -i /etc/lsb-release \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=cachyos|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"CachyOS\"|'
}

update_os_release() {
    local os_release="/etc/os-release"
    sed -i "$os_release" \
        -e 's|^NAME=.*$|NAME=\"CachyOS Linux\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"CachyOS\"|' \
        -e 's|^ID=.*$|ID=cachyos|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^ANSI_COLOR=.*$|ANSI_COLOR=\"38;2;23;147;209\"|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://cachyos.org/\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://wiki.cachyos.org/\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://discuss.cachyos.org/\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/cachyos\"|' \
        -e 's|^LOGO=.*$|LOGO=cachyos|'

    # add missing ID_LIKE=
    if ! grep -q "^ID_LIKE=" "$os_release" && ! grep -q "^ID=" "$os_release"; then
        sed -i "$os_release" -e '/^ID=/a \ID_LIKE=arch'
    fi
}

update_issues() {
    sed -i 's|Arch Linux|CachyOS Linux|g' /etc/issue /usr/share/factory/etc/issue
}

case "$1" in
    os-release) update_os_release ;;
    lsb-release) update_lsb_release ;;
    *)
        update_os_release
        update_lsb_release
        update_issues
        ;;
esac
